import { writeFileSync, mkdirSync } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Pixel values mirror src/breakpoints.value.tokens.json.
// @media rules can't use CSS custom properties, so they are inlined here.
const BP_MD = '1008px'; // --breakpoint-md  tablet max-width
const BP_SM = '641px'; // --breakpoint-sm  mobile max-width

const TYPO_PROPS = [
  ['font-family', 'fontFamily'],
  ['font-size', 'fontSize'],
  ['font-weight', 'fontWeight'],
  ['line-height', 'lineHeight'],
  ['text-transform', 'textTransform'],
  ['letter-spacing', 'letterSpacing'],
  ['text-decoration', 'textDecoration'],
];

// Emit typography custom property references for a given --text-style-* prefix.
// indent is prepended before each property line (use '  ' inside @media blocks).
function typo(prefix, indent = '') {
  return TYPO_PROPS.map(([cssProp]) => `${indent}  ${cssProp}: var(--${prefix}-${cssProp});`).join(
    '\n',
  );
}

const css = `/**
 * ABC Reset Styles
 * Auto-generated by reset.js — do not edit manually.
 * Requires dist/tokens.css (run: npm run build first).
 */

@import url('./tokens.css');

/* ── Box model ─────────────────────────────────────────────────── */

*,
*::before,
*::after {
  box-sizing: border-box;
}

/* ── Base ──────────────────────────────────────────────────────── */

html {
  font-size: 18px;
}

body {
  display: none;
  margin: 0;
  font-family: var(--text-style-base-paragraph-font-family);
  font-size: var(--text-style-base-paragraph-font-size);
  font-weight: var(--text-style-base-paragraph-font-weight);
  line-height: var(--text-style-base-paragraph-line-height);
  color: var(--color-text-primary);
  background-color: var(--color-background-primary);
}

/* ── Headings ──────────────────────────────────────────────────── */

h1, h2, h3, h4, h5, h6 {
  margin: 0;
}

h1 {
${typo('text-style-base-h1')}
}

h2 {
${typo('text-style-base-h2')}
}

h3 {
${typo('text-style-base-h3')}
}

h4 {
${typo('text-style-base-h4')}
}

h5 {
${typo('text-style-base-h5')}
}

h6 {
${typo('text-style-base-h6')}
}

/* ── Paragraph ─────────────────────────────────────────────────── */

p {
  margin: 0;
${typo('text-style-base-paragraph')}
}

/* ── Links ─────────────────────────────────────────────────────── */

a {
${typo('text-style-other-text-link').replace('  text-transform:', '  color: var(--color-link-default);\n  text-transform:')}
}

a:hover {
  color: var(--color-link-state-hover);
}

/* ── Responsive typography — mobile (< ${BP_SM}) ──────────────── */

@media (width < ${BP_SM}) {
  h1 {
${typo('text-style-small-h1-small', '  ')}
  }

  h2 {
${typo('text-style-small-h2-small', '  ')}
  }

  h3 {
${typo('text-style-small-h3-small', '  ')}
  }
}

/* ── Grid container ────────────────────────────────────────────── */

.grid-container {
  display: grid;
  grid-template-columns: repeat(var(--grid-desktop-columns), 1fr);
  gap: var(--grid-desktop-gutter);
  padding-inline: var(--grid-desktop-offset);
}

@media (width < ${BP_MD}) {
  .grid-container {
    grid-template-columns: repeat(var(--grid-tablet-columns), 1fr);
    gap: var(--grid-tablet-gutter);
    padding-inline: var(--grid-tablet-offset);
  }
}

@media (width < ${BP_SM}) {
  .grid-container {
    grid-template-columns: repeat(var(--grid-mobile-columns), 1fr);
    gap: var(--grid-mobile-gutter);
    padding-inline: var(--grid-mobile-offset);
  }
}
`;

mkdirSync(path.join(__dirname, 'dist'), { recursive: true });
writeFileSync(path.join(__dirname, 'dist', 'reset.css'), css);
console.log('✓  dist/reset.css generated');
