import { writeFileSync, mkdirSync } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Pixel values mirror src/breakpoints.value.tokens.json.
// @media rules can't use CSS custom properties, so they are inlined here.
// Mobile-first: base styles target mobile, these are the min-widths where
// tablet and desktop styles kick in.
const BP_SM = '641px'; // --breakpoint-sm  tablet min-width
const BP_MD = '1008px'; // --breakpoint-md  desktop min-width

const TYPO_PROPS = [
  ['font-family', 'fontFamily'],
  ['font-size', 'fontSize'],
  ['font-weight', 'fontWeight'],
  ['line-height', 'lineHeight'],
  ['text-transform', 'textTransform'],
  ['letter-spacing', 'letterSpacing'],
  ['text-decoration', 'textDecoration'],
];

// Emit typography custom property references for a given --text-style-* prefix.
// indent is prepended before each property line (use '  ' inside @media blocks).
function typo(prefix, indent = '') {
  return TYPO_PROPS.map(([cssProp]) => `${indent}  ${cssProp}: var(--${prefix}-${cssProp});`).join(
    '\n',
  );
}

// h1-h3 are the only headings whose size differs between mobile and
// tablet/desktop (h4-h6 and paragraph share the same value at every
// breakpoint per src/typography.mobile.tokens.json vs typography.desktop.tokens.json).
// Mobile-first base: font-family/font-weight/text-transform/letter-spacing/text-decoration
// come from the breakpoint-invariant text-style-base-h* tokens; font-size,
// line-height, and margin-bottom come from the mobile typography tokens.
function mobileHeading(n) {
  const base = `text-style-base-h${n}`;
  return [
    `  font-family: var(--${base}-font-family);`,
    `  font-size: var(--typography-mobile-h${n});`,
    `  font-weight: var(--${base}-font-weight);`,
    `  line-height: var(--typography-mobile-line-height-h${n});`,
    `  text-transform: var(--${base}-text-transform);`,
    `  letter-spacing: var(--${base}-letter-spacing);`,
    `  text-decoration: var(--${base}-text-decoration);`,
    `  margin-bottom: var(--typography-mobile-default-margin-bottom-h${n});`,
  ].join('\n');
}

// Tablet/desktop override: only font-size, line-height, and margin-bottom
// change — swap them for the desktop typography tokens.
function desktopHeadingOverride(n) {
  return [
    `    font-size: var(--text-style-base-h${n}-font-size);`,
    `    line-height: var(--text-style-base-h${n}-line-height);`,
    `    margin-bottom: var(--typography-desktop-default-margin-bottom-h${n});`,
  ].join('\n');
}

const css = `/**
 * ABC Reset Styles
 * Auto-generated by reset.js — do not edit manually.
 * Requires dist/tokens.css (run: npm run build first).
 */

@import url('./tokens.css');

/* ── Box model ─────────────────────────────────────────────────── */

*,
*::before,
*::after {
  box-sizing: border-box;
}

/* ── Base ──────────────────────────────────────────────────────── */

html {
  font-size: 18px;
}

body {
  display: none;
  margin: 0;
  font-family: var(--text-style-base-paragraph-font-family);
  font-size: var(--text-style-base-paragraph-font-size);
  font-weight: var(--text-style-base-paragraph-font-weight);
  line-height: var(--text-style-base-paragraph-line-height);
  color: var(--color-text-primary);
  background-color: var(--color-background-primary);
}

/* ── Headings ──────────────────────────────────────────────────── */

h1, h2, h3, h4, h5, h6 {
  margin: 0;
}

h1 {
${mobileHeading(1)}
}

h2 {
${mobileHeading(2)}
}

h3 {
${mobileHeading(3)}
}

h4 {
${typo('text-style-base-h4')}
  margin-bottom: var(--typography-mobile-default-margin-bottom-h4);
}

h5 {
${typo('text-style-base-h5')}
  margin-bottom: var(--typography-mobile-default-margin-bottom-h5);
}

h6 {
${typo('text-style-base-h6')}
  margin-bottom: var(--typography-mobile-default-margin-bottom-h6);
}

/* ── Paragraph ─────────────────────────────────────────────────── */

p {
  margin: 0;
${typo('text-style-base-paragraph')}
  margin-bottom: var(--typography-mobile-default-margin-bottom-paragraph);
  max-width: var(--typography-mobile-line-length-paragraph-max-width);
}

/* ── Links ─────────────────────────────────────────────────────── */

a {
${typo('text-style-other-text-link').replace('  text-transform:', '  color: var(--color-link-default);\n  text-transform:')}
}

a:hover {
  color: var(--color-link-state-hover);
}

/* ── Divider ───────────────────────────────────────────────────── */

hr {
  height: 0;
  margin: 0;
  border: 0;
  border-top: calc(var(--color-divider-weight-light) * 1px) var(--color-divider-border-style) var(--color-divider-default);
}

/* ── Media ─────────────────────────────────────────────────────── */

img,
svg,
video {
  display: block;
  max-width: 100%;
}

/* ── Forms ─────────────────────────────────────────────────────── */

button,
input,
select,
textarea {
  font: inherit;
  color: inherit;
}

/* ── Focus ─────────────────────────────────────────────────────── */

:focus-visible {
  outline: var(--border-width-50) solid var(--color-border-state-focus);
  outline-offset: var(--border-width-50);
}

/* ── Responsive typography — tablet & desktop (>= ${BP_SM}) ────── */

@media (width >= ${BP_SM}) {
  h1 {
${desktopHeadingOverride(1)}
  }

  h2 {
${desktopHeadingOverride(2)}
  }

  h3 {
${desktopHeadingOverride(3)}
  }
}

/* ── Grid container ────────────────────────────────────────────── */

.grid-container {
  display: grid;
  grid-template-columns: repeat(var(--grid-mobile-columns), 1fr);
  gap: var(--grid-mobile-gutter);
  padding-inline: var(--grid-mobile-offset);
}

@media (width >= ${BP_SM}) {
  .grid-container {
    grid-template-columns: repeat(var(--grid-tablet-columns), 1fr);
    gap: var(--grid-tablet-gutter);
    padding-inline: var(--grid-tablet-offset);
  }
}

@media (width >= ${BP_MD}) {
  .grid-container {
    grid-template-columns: repeat(var(--grid-desktop-columns), 1fr);
    gap: var(--grid-desktop-gutter);
    padding-inline: var(--grid-desktop-offset);
  }
}
`;

mkdirSync(path.join(__dirname, 'dist'), { recursive: true });
writeFileSync(path.join(__dirname, 'dist', 'reset.css'), css);
console.log('✓  dist/reset.css generated');
